const data = [
    {
        mainCoverImage: process.env.PUBLIC_URL + "/images/employee crud/Capture.PNG",
        title: "An Employee Management System",
        desc: "I used Nextjs, Postgresql,Nodejs and ExpressJs for this project. It allows ease of managing employees",
        subImages2: process.env.PUBLIC_URL + "/images/employee crud/Capture2.PNG",
        subImages3: process.env.PUBLIC_URL + "/images/employee crud/Capture3.PNG",
        subImages4: process.env.PUBLIC_URL + "/images/employee crud/Capture4.PNG",
        subImages5: process.env.PUBLIC_URL + "/images/employee crud/Capture5.PNG",
        linkToWeb: "#",
        linkToGithub: 'https://github.com/jewtechx/employees-management-system',
    },
    {
        mainCoverImage:process.env.PUBLIC_URL + "/images/blogPortfolio/blog1.PNG",
        title: "A Personal Blog Website",
        desc: "This project was created with pure html , css and js. It a fully responsive static blog website. I adhered to all design priciples and rules",
        subImages2: process.env.PUBLIC_URL + "/images/blogPortfolio/blog2.PNG",
        subImages3: process.env.PUBLIC_URL + "/images/blogPortfolio/blog3.PNG",
        subImages4: process.env.PUBLIC_URL + "/images/blogPortfolio/blog4.PNG",
        subImages5: process.env.PUBLIC_URL + "/images/blogPortfolio/blog5.PNG",
        linkToWeb: "#",
        linkToGithub: 'https://github.com/jewtechx/BlogWebsite',
    },
    {
        mainCoverImage: process.env.PUBLIC_URL + "/images/nasa/nasa1.png",
        title: "Nasa Mission Control System",
        desc: "A full crud app that allows nasa mission admins to schedule and abort mission. It keeps track of the history too",
        subImages2: process.env.PUBLIC_URL + "/images/nasa/nasa2.png",
        subImages3: process.env.PUBLIC_URL + "/images/nasa/nasa3.png",
        subImages4: process.env.PUBLIC_URL + "/images/nasa/nasa1.png",
        subImages5: process.env.PUBLIC_URL + "/images/nasa/nasa3.png",
        linkToWeb: "#",
        linkToGithub: 'https://github.com/jewtechx/nasa-mission-control-system',
    },
    {
        mainCoverImage: process.env.PUBLIC_URL + "/images/backerchain/backerchain1.JPG",
        title: "BackerChain Crowfunding",
        desc: "This websites allows funders to support start-ups with SOL transparently and at low transaction costs.",
        subImages2: process.env.PUBLIC_URL + "/images/backerchain/backerchain2.JPG",
        subImages3: process.env.PUBLIC_URL + "/images/backerchain/backerchain3.JPG",
        subImages4: process.env.PUBLIC_URL + "/images/backerchain/backerchain4.JPG",
        subImages5: process.env.PUBLIC_URL + "/images/backerchain/backerChain5.JPG",
        linkToWeb: "#",
        linkToGithub: 'https://github.com/jewtechx/backerchain',
    },
]
export default data