const data = [
    {
        mainCoverImage: "/images/employee crud/Capture.PNG",
        title: "An Employee Management System",
        desc: "I used Nextjs, Postgresql,Nodejs and ExpressJs for this project. It allows ease of managing employees",
        subImages2: "/images/employee crud/Capture2.PNG",
        subImages3: "/images/employee crud/Capture3.PNG",
        subImages4: "/images/employee crud/Capture4.PNG",
        subImages5: "/images/employee crud/Capture5.PNG",
        linkToWeb: "#",
        linkToGithub: 'https://github.com/jewtechx/employees-management-system',
    },
    {
        mainCoverImage: "/images/blogPortfolio/blog1.png",
        title: "A Personal Blog Website",
        desc: "This project was created with pure html , css and js. It a fully responsive static blog website. I adhered to all design priciples and rules",
        subImages2: "/images/blogPortfolio/blog2.png",
        subImages3: "/images/blogPortfolio/blog3.png",
        subImages4: "/images/blogPortfolio/blog4.png",
        subImages5: "/images/blogPortfolio/blog5.png",
        linkToWeb: "#",
        linkToGithub: 'https://github.com/jewtechx/BlogWebsite',
    },
    {
        mainCoverImage: "/images/nasa/nasa1.png",
        title: "Nasa Mission Control System",
        desc: "A full crud app that allows nasa mission admins schedule and abort mission. It keeps track of the history too",
        subImages2: "/images/nasa/nasa2.png",
        subImages3: "/images/nasa/nasa3.png",
        subImages4: "/images/nasa/nasa1.png",
        subImages5: "/images/nasa/nasa3.png",
        linkToWeb: "#",
        linkToGithub: 'https://github.com/jewtechx/nasa-mission-control-system',
    },
]
export default data